### ISSUE TITLE
Documentation to move to BU-specific repository

### ISSUE THREAD

**Issue by ashleykolodziej** [bu-ist/responsive-framework#135]
As I'm scrubbing documentation, the following pages contain BU-specific documentation that should be moved to either the new child theme or plugin in preparation for open sourcing:

- [ ] https://github.com/bu-ist/responsive-framework/wiki/Responsive-Video-Shortcode
- [ ] https://github.com/bu-ist/responsive-framework/wiki/PHP-Snippets
- [ ] https://github.com/bu-ist/responsive-framework/wiki/Shortcodes
- [ ] https://github.com/bu-ist/responsive-framework/wiki/TEMP-PHP-Code-Patterns
- [ ] https://github.com/bu-ist/responsive-framework/wiki/Testing-your-changes
- [ ] https://github.com/bu-ist/responsive-framework/wiki/Icon-Font
- [ ] https://github.com/bu-ist/responsive-framework/wiki/Code-patterns
- [ ] https://github.com/bu-ist/responsive-framework/wiki/Customizing-CSS-in-a-child-theme
- [ ] https://github.com/bu-ist/responsive-framework/wiki/Overriding-templates-in-a-child-theme
- [ ] https://github.com/bu-ist/responsive-framework/wiki/Flexi-Migrations
- [ ] https://github.com/bu-ist/responsive-framework/wiki/Configure-Grunt

**Comment by toddmilliken** [comment]
The plugin for this has been setup here: https://github.com/bu-ist/bu-responsive-customizations so we can begin migrating these. 😄

**Comment by aremery** [comment]
I added the wiki pages to the wiki for the plugin. https://github.com/bu-ist/bu-responsive-customizations/wiki

**Comment by ashleykolodziej** [comment]
@aremery Can you update the content on the pages above to say the following in this repo?

> This documentation has been moved to the `bu-responsive-customizations` repository at (whatever the new link is for each page) as part of our open source initiative, and will be deleted on July 1st, 2019. Please update your bookmarks accordingly.

Thank you!

**Comment by acketon** [comment]
This looks like it was completed 3 years ago. closing this issue.
